### ISSUE TITLE
Username links

### ISSUE THREAD

**Issue by ANDREYDEN** [FRFlor/vehikl-growth-sessions#38]
Would be cool to be able to go to the users' GH profiles when clicking on their names/avatars.

**Comment by ANDREYDEN** [comment]
@FRFlor, do you mind if I tackle this?

**Comment by FRFlor** [comment]
@ANDREYDEN Sounds good. 

I think this should probably appear only on the growth session page itself, do you agree?

In other words, I  don't think this should happen when clicking on the avatar inside the cards that appear on the week view. 

Do you agree?

**Comment by ANDREYDEN** [comment]
Yep, that makes sense. On it
