### ISSUE TITLE
Week selection persistence

### ISSUE THREAD

**Issue by ANDREYDEN** [FRFlor/vehikl-growth-sessions#48]
**Steps to reproduce:**
- select a week different from the current one
- select any growth session (go into `SocialMobView`)
- go back in browser

**Outcome:** 
You end up on the current week

**Intended outcome**
You should remain on the previously selected week

**Comment by FRFlor** [comment]
Totally agree, that is something that annoys me too. 

Do you want to tackle that? 

Or maybe we can setup a Growth Session on it. Whatever is best.

**Comment by ANDREYDEN** [comment]
I think you would need to use the `history` API and bind the back and forward buttons to the browser buttons. A Growth Session would be cool.
