### ISSUE TITLE
Editing a mob with no attendee limit

### ISSUE THREAD

**Issue by ANDREYDEN** [FRFlor/vehikl-growth-sessions#50]
### Current behaviour
When editing a mob, it always defaults to a limit of 4 attendees regardless of the limit that was previously set.

### Desired behaviour
When editing a mob, the editing form should display the current attendee limit of the mob.

**Comment by FRFlor** [comment]
The update social mob limit wasn't implemented yet. We just pushed the one that allows you to create a social mob with a given attendee limit. 

As you can see here, the update request doesn't even recognize a limit update yet. 

![image](https://user-images.githubusercontent.com/22578748/96536273-abe56f80-1261-11eb-8145-26050158011b.png)

We could mob on this during together a growth session

**Comment by ANDREYDEN** [comment]
Oh, right, I see. Sorry, I got confused, I'm down for a growth session though.

**Comment by FRFlor** [comment]
Thanks Andrii! This issue has been resolved.
